## Spring Properties
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/schedule_db
    username: admin
    password: admin
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
    ## Log SQL statements and parameters output
    show-sql: true
    properties.hibernate.format_sql: true
  sql:
    init:
      mode: always
server:
  port: 8080